/* Generated By:JavaCC: Do not edit this line. HLTreeConstants.java Version 5.0 */
public interface HLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTVAR_DECL = 1;
  public int JJTIDENT_LIST = 2;
  public int JJTBOOLTYPE = 3;
  public int JJTPOLTYPE = 4;
  public int JJTINTTYPE = 5;
  public int JJTFN_DECL = 6;
  public int JJTPARAM_DECLS = 7;
  public int JJTPARAM_DECL = 8;
  public int JJTBODY = 9;
  public int JJTASSIGNMENT = 10;
  public int JJTIF_STAT = 11;
  public int JJTCLAUSE = 12;
  public int JJTFOR_STAT = 13;
  public int JJTFOREACH_STAT = 14;
  public int JJTWHILE_STAT = 15;
  public int JJTPRINTFN_CALL = 16;
  public int JJTPRINTLNFN_CALL = 17;
  public int JJTFN_CALL = 18;
  public int JJTPARAMETERS = 19;
  public int JJTSTOP_STAT = 20;
  public int JJTRETURN_STAT = 21;
  public int JJTNOTHING = 22;
  public int JJTPRINT_STAT = 23;
  public int JJTCOMPARISON = 24;
  public int JJTEQ = 25;
  public int JJTNE = 26;
  public int JJTGE = 27;
  public int JJTGT = 28;
  public int JJTLE = 29;
  public int JJTLT = 30;
  public int JJTISATYPE = 31;
  public int JJTINDEXED = 32;
  public int JJTEXP = 33;
  public int JJTPOLYN = 34;
  public int JJTMINUS = 35;
  public int JJTTEST = 36;
  public int JJTIDENTIFIER = 37;
  public int JJTINTEGER = 38;
  public int JJTBOOL = 39;
  public int JJTSTRING = 40;
  public int JJTPLUS = 41;


  public String[] jjtNodeName = {
    "void",
    "var_decl",
    "ident_list",
    "boolType",
    "polType",
    "intType",
    "fn_decl",
    "param_decls",
    "param_decl",
    "body",
    "assignment",
    "if_stat",
    "clause",
    "for_stat",
    "foreach_stat",
    "while_stat",
    "printfn_call",
    "printlnfn_call",
    "fn_call",
    "parameters",
    "stop_stat",
    "return_stat",
    "NOTHING",
    "print_stat",
    "comparison",
    "EQ",
    "NE",
    "GE",
    "GT",
    "LE",
    "LT",
    "isatype",
    "indexed",
    "exp",
    "polyn",
    "minus",
    "test",
    "identifier",
    "integer",
    "bool",
    "string",
    "plus",
  };
}
/* JavaCC - OriginalChecksum=547dd4b92353187a277e23f47521e83d (do not edit this line) */
