/* Generated By:JJTree: Do not edit this line. ASTBOOL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBOOL extends SimpleNode {
  public ASTBOOL(int id) {
    super(id);
  }

  public ASTBOOL(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=69cf1b34ac40f2f16cb43dde6355ac59 (do not edit this line) */
