/* Generated By:JJTree: Do not edit this line. ASTfn_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfn_decl extends SimpleNode {
  public ASTfn_decl(int id) {
    super(id);
  }

  public ASTfn_decl(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bcf6e5c944f6435df21628a1b2c52a78 (do not edit this line) */
