/* Generated By:JJTree: Do not edit this line. ASTparameters.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparameters extends SimpleNode {
  public ASTparameters(int id) {
    super(id);
  }

  public ASTparameters(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=96bf773f9dd08ec0edc52ec7c8c63c4f (do not edit this line) */
