/* Generated By:JJTree: Do not edit this line. ASTproduct.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTproduct extends SimpleNode {
  public ASTproduct(int id) {
    super(id);
  }

  public ASTproduct(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5434f8c5d747a6bb732a304ec57b878c (do not edit this line) */
