/* Generated By:JJTree: Do not edit this line. ASTreturn_stat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreturn_stat extends SimpleNode {
  public ASTreturn_stat(int id) {
    super(id);
  }

  public ASTreturn_stat(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=563d579068dc7c4b1c855b5edfb7c103 (do not edit this line) */
