/* Generated By:JJTree: Do not edit this line. ASTstop_stat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstop_stat extends SimpleNode {
  public ASTstop_stat(int id) {
    super(id);
  }

  public ASTstop_stat(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=98068c8965738c5978b925acceb02236 (do not edit this line) */
