/* Generated By:JJTree&JavaCC: Do not edit this line. HLConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LT = 7;
  /** RegularExpression Id. */
  int LE = 8;
  /** RegularExpression Id. */
  int GT = 9;
  /** RegularExpression Id. */
  int GE = 10;
  /** RegularExpression Id. */
  int NE = 11;
  /** RegularExpression Id. */
  int EQ = 12;
  /** RegularExpression Id. */
  int ADD = 13;
  /** RegularExpression Id. */
  int SUB = 14;
  /** RegularExpression Id. */
  int PROD = 15;
  /** RegularExpression Id. */
  int DIV = 16;
  /** RegularExpression Id. */
  int EXP = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;
  /** RegularExpression Id. */
  int LPAREN = 19;
  /** RegularExpression Id. */
  int RPAREN = 20;
  /** RegularExpression Id. */
  int LSQUARE = 21;
  /** RegularExpression Id. */
  int RSQUARE = 22;
  /** RegularExpression Id. */
  int COMMA = 23;
  /** RegularExpression Id. */
  int SEMICOL = 24;
  /** RegularExpression Id. */
  int AND = 25;
  /** RegularExpression Id. */
  int AS = 26;
  /** RegularExpression Id. */
  int BOOL = 27;
  /** RegularExpression Id. */
  int BY = 28;
  /** RegularExpression Id. */
  int DEC = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int ELIF = 31;
  /** RegularExpression Id. */
  int ELSE = 32;
  /** RegularExpression Id. */
  int FI = 33;
  /** RegularExpression Id. */
  int FOR = 34;
  /** RegularExpression Id. */
  int FOREACH = 35;
  /** RegularExpression Id. */
  int FROM = 36;
  /** RegularExpression Id. */
  int FUN = 37;
  /** RegularExpression Id. */
  int IF = 38;
  /** RegularExpression Id. */
  int IN = 39;
  /** RegularExpression Id. */
  int INT = 40;
  /** RegularExpression Id. */
  int ISA = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int NUF = 43;
  /** RegularExpression Id. */
  int OD = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int POLYN = 46;
  /** RegularExpression Id. */
  int PRINT = 47;
  /** RegularExpression Id. */
  int RETURN = 48;
  /** RegularExpression Id. */
  int STOP = 49;
  /** RegularExpression Id. */
  int THEN = 50;
  /** RegularExpression Id. */
  int TO = 51;
  /** RegularExpression Id. */
  int VAR = 52;
  /** RegularExpression Id. */
  int WHILE = 53;
  /** RegularExpression Id. */
  int X = 54;
  /** RegularExpression Id. */
  int INTEGER = 55;
  /** RegularExpression Id. */
  int DECIMAL = 56;
  /** RegularExpression Id. */
  int BOOLEAN = 57;
  /** RegularExpression Id. */
  int STRING = 58;
  /** RegularExpression Id. */
  int IDENTIFIER = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"<>\"",
    "\"==\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\"and\"",
    "\"as\"",
    "\"bool\"",
    "\"by\"",
    "\"dec\"",
    "\"do\"",
    "\"elif\"",
    "\"else\"",
    "\"fi\"",
    "\"for\"",
    "\"foreach\"",
    "\"from\"",
    "\"fun\"",
    "\"if\"",
    "\"in\"",
    "\"int\"",
    "\"isa\"",
    "\"not\"",
    "\"nuf\"",
    "\"od\"",
    "\"or\"",
    "\"polyn\"",
    "\"print\"",
    "\"return\"",
    "\"stop\"",
    "\"then\"",
    "\"to\"",
    "\"var\"",
    "\"while\"",
    "\"x\"",
    "<INTEGER>",
    "<DECIMAL>",
    "<BOOLEAN>",
    "<STRING>",
    "<IDENTIFIER>",
  };

}
