/* Generated By:JavaCC: Do not edit this line. HLVisitor.java Version 5.0 */
public interface HLVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTvar_decl node, Object data);
  public Object visit(ASTindent_list node, Object data);
  public Object visit(ASTidentlist node, Object data);
  public Object visit(ASTINT node, Object data);
  public Object visit(ASTBOOL node, Object data);
  public Object visit(ASTPOL node, Object data);
  public Object visit(ASTfn_decl node, Object data);
  public Object visit(ASTNOTHING node, Object data);
  public Object visit(ASTparam_decls node, Object data);
  public Object visit(ASTbody node, Object data);
  public Object visit(ASTassignment node, Object data);
  public Object visit(ASTif_stat node, Object data);
  public Object visit(ASTclause node, Object data);
  public Object visit(ASTfor_stat node, Object data);
  public Object visit(ASTforeach_stat node, Object data);
  public Object visit(ASTwhile_stat node, Object data);
  public Object visit(ASTfn_call node, Object data);
  public Object visit(ASTparameters node, Object data);
  public Object visit(ASTstop_stat node, Object data);
  public Object visit(ASTreturn_stat node, Object data);
  public Object visit(ASTprint_stat node, Object data);
  public Object visit(ASTisa node, Object data);
  public Object visit(ASTEQ node, Object data);
  public Object visit(ASTLT node, Object data);
  public Object visit(ASTGT node, Object data);
  public Object visit(ASTLE node, Object data);
  public Object visit(ASTGE node, Object data);
  public Object visit(ASTNE node, Object data);
  public Object visit(ASTplus node, Object data);
  public Object visit(ASTminus node, Object data);
  public Object visit(ASTsum node, Object data);
  public Object visit(ASTtimes node, Object data);
  public Object visit(ASTdiv node, Object data);
  public Object visit(ASTproduct node, Object data);
  public Object visit(ASTexp node, Object data);
  public Object visit(ASTindexed node, Object data);
  public Object visit(ASTpolyn node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTString node, Object data);
}
/* JavaCC - OriginalChecksum=23073d1d4734af434858a4c360f5fc01 (do not edit this line) */
