/* Generated By:JJTree: Do not edit this line. ASTindexed.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTindexed extends SimpleNode {
  public ASTindexed(int id) {
    super(id);
  }

  public ASTindexed(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a30f2f6712cc560b3d8ae716d84eaee4 (do not edit this line) */
