/* Generated By:JJTree: Do not edit this line. ASTindent_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTindent_list extends SimpleNode {
  public ASTindent_list(int id) {
    super(id);
  }

  public ASTindent_list(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=13a8d4a355b0d00bcdff2fd57fa3f0c6 (do not edit this line) */
