/* Generated By:JJTree: Do not edit this line. ASTtimes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtimes extends SimpleNode {
  public ASTtimes(int id) {
    super(id);
  }

  public ASTtimes(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cffb7ef4bffa04d21738abefb0e3ba52 (do not edit this line) */
