/* Generated By:JJTree: Do not edit this line. ASTwhile_stat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwhile_stat extends SimpleNode {
  public ASTwhile_stat(int id) {
    super(id);
  }

  public ASTwhile_stat(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b2384201f3b31c873da55b9fd05f290d (do not edit this line) */
