/* Generated By:JavaCC: Do not edit this line. HLTreeConstants.java Version 5.0 */
public interface HLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTVAR_DECL = 1;
  public int JJTINDENT_LIST = 2;
  public int JJTIDENTLIST = 3;
  public int JJTINT = 4;
  public int JJTBOOL = 5;
  public int JJTPOL = 6;
  public int JJTFN_DECL = 7;
  public int JJTNOTHING = 8;
  public int JJTPARAM_DECLS = 9;
  public int JJTBODY = 10;
  public int JJTASSIGNMENT = 11;
  public int JJTIF_STAT = 12;
  public int JJTCLAUSE = 13;
  public int JJTFOR_STAT = 14;
  public int JJTFOREACH_STAT = 15;
  public int JJTWHILE_STAT = 16;
  public int JJTFN_CALL = 17;
  public int JJTPARAMETERS = 18;
  public int JJTSTOP_STAT = 19;
  public int JJTRETURN_STAT = 20;
  public int JJTPRINT_STAT = 21;
  public int JJTISA = 22;
  public int JJTEQ = 23;
  public int JJTLT = 24;
  public int JJTGT = 25;
  public int JJTLE = 26;
  public int JJTGE = 27;
  public int JJTNE = 28;
  public int JJTPLUS = 29;
  public int JJTMINUS = 30;
  public int JJTSUM = 31;
  public int JJTTIMES = 32;
  public int JJTDIV = 33;
  public int JJTPRODUCT = 34;
  public int JJTEXP = 35;
  public int JJTINDEXED = 36;
  public int JJTPOLYN = 37;
  public int JJTIDENTIFIER = 38;
  public int JJTINTEGER = 39;
  public int JJTSTRING = 40;


  public String[] jjtNodeName = {
    "void",
    "var_decl",
    "indent_list",
    "identlist",
    "INT",
    "BOOL",
    "POL",
    "fn_decl",
    "NOTHING",
    "param_decls",
    "body",
    "assignment",
    "if_stat",
    "clause",
    "for_stat",
    "foreach_stat",
    "while_stat",
    "fn_call",
    "parameters",
    "stop_stat",
    "return_stat",
    "print_stat",
    "isa",
    "EQ",
    "LT",
    "GT",
    "LE",
    "GE",
    "NE",
    "plus",
    "minus",
    "sum",
    "times",
    "div",
    "product",
    "exp",
    "indexed",
    "polyn",
    "Identifier",
    "Integer",
    "String",
  };
}
/* JavaCC - OriginalChecksum=5d45be8825632020a21d54b7a44834f4 (do not edit this line) */
